# Generated by Django 5.2.3 on 2025-12-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunningBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('carries', models.IntegerField()),
                ('yards', models.IntegerField()),
            ],
            options={
                'db_table': 'rushing',
            },
        ),
    ]
